---
deployment:
  tasks:
    - export GOPATH=$HOME/go
    - export PATH=$GOPATH/bin:$PATH
    - /opt/cpanel/ea-nodejs18/bin/npm install -g serve || true  # workaround for PATH issues
    - cd $DEPLOYMENT_SOURCE
    - go mod tidy
    - go build -o app
    - pkill app || true
    - nohup ./app > output.log 2>&1 &
