---
deployment:
  tasks:
    - export PATH=$HOME/go/bin:$PATH
    - echo "Building Go app..."
    - go mod tidy
    - go build -o myapp main.go
    - echo "Deploying..."
    - cp myapp ~/public_html/prod/
